import path from 'node:path';
import fs from 'fs-extra';
import type { AgentStdConfig } from '../../core/config';
import { permissionsOf } from '../../core/config-defaults';
import { codexAgentStdRulesPath } from '../../core/paths';
import type { FileOperation } from '../../core/types';

export async function syncCodexRules(
  outputRoot: string,
  config: AgentStdConfig,
  operations: FileOperation[],
  dryRun?: boolean,
): Promise<string[]> {
  const rules = renderCodexRules(config);
  const filePath = codexAgentStdRulesPath(outputRoot);
  const current = await fs.readFile(filePath, 'utf8').catch(() => null);
  if (!rules) {
    if (current === null) return [];
    operations.push({
      type: 'remove-file',
      path: path.relative(outputRoot, filePath) || filePath,
    });
    if (!dryRun) await fs.remove(filePath);
    return ['.codex/rules/agentstd.rules'];
  }

  if (current === rules) {
    operations.push({
      type: 'skip',
      description: '.codex/rules/agentstd.rules',
      reason: 'Codex rules already synced',
    });
    return [];
  }

  operations.push({
    type: current === null ? 'create-file' : 'update-file',
    path: path.relative(outputRoot, filePath) || filePath,
  });
  if (!dryRun) {
    await fs.ensureDir(path.dirname(filePath));
    await fs.writeFile(filePath, rules);
  }
  return ['.codex/rules/agentstd.rules'];
}

function renderCodexRules(config: AgentStdConfig): string {
  const permissions = permissionsOf(config);
  const lines = [
    '# Generated by AgentStd. Edit .agentstd.yaml instead.',
    '',
    ...permissions.commands.allow.map((pattern) => renderPrefixRule(pattern, 'allow')),
    ...permissions.commands.prompt.map((pattern) => renderPrefixRule(pattern, 'prompt')),
    ...permissions.commands.deny.map((pattern) => renderPrefixRule(pattern, 'forbidden')),
  ];
  const content = lines.join('\n').trim();
  return content === '# Generated by AgentStd. Edit .agentstd.yaml instead.' ? '' : `${content}\n`;
}

function renderPrefixRule(pattern: string[], decision: string): string {
  const renderedPattern = `[${pattern.map((part) => JSON.stringify(part)).join(', ')}]`;
  return `prefix_rule(pattern = ${renderedPattern}, decision = ${JSON.stringify(decision)})\n`;
}
